In [1]:
import pandas as pd
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
x=iris.data

In [4]:
y=iris.target

In [5]:
df=pd.DataFrame(x)

In [6]:
df['target']=iris.target
df.shape

(150, 5)

In [7]:
from sklearn.model_selection import train_test_split

In [16]:
X,x,Y,y=train_test_split(df.drop('target',axis=1),df.target,test_size=0.2)

df_train=pd.DataFrame(X)
df_train['target']=Y
print(df_train)

df_test=pd.DataFrame(x)
df_test['target']=y
df_test

       0    1    2    3 named_target  target
137  6.4  3.1  5.5  1.8    virginica       2
116  6.5  3.0  5.5  1.8    virginica       2
131  7.9  3.8  6.4  2.0    virginica       2
30   4.8  3.1  1.6  0.2       setosa       0
62   6.0  2.2  4.0  1.0   versicolor       1
..   ...  ...  ...  ...          ...     ...
83   6.0  2.7  5.1  1.6   versicolor       1
31   5.4  3.4  1.5  0.4       setosa       0
108  6.7  2.5  5.8  1.8    virginica       2
120  6.9  3.2  5.7  2.3    virginica       2
135  7.7  3.0  6.1  2.3    virginica       2

[120 rows x 6 columns]

       0    1    2    3 named_target  target
79   5.7  2.6  3.5  1.0   versicolor       1
138  6.0  3.0  4.8  1.8    virginica       2
107  7.3  2.9  6.3  1.8    virginica       2
125  7.2  3.2  6.0  1.8    virginica       2
90   5.5  2.6  4.4  1.2   versicolor       1
144  6.7  3.3  5.7  2.5    virginica       2
67   5.8  2.7  4.1  1.0   versicolor       1
95   5.7  3.0  4.2  1.2   versicolor       1
148  6.2  3.4  5.4  2.3    virginica       2
118  7.7  2.6  6.9  2.3    virginica       2
54   6.5  2.8  4.6  1.5   versicolor       1
136  6.3  3.4  5.6  2.4    virginica       2
3    4.6  3.1  1.5  0.2       setosa       0
19   5.1  3.8  1.5  0.3       setosa       0
7    5.0  3.4  1.5  0.2       setosa       0
65   6.7  3.1  4.4  1.4   versicolor       1
9    4.9  3.1  1.5  0.1       setosa       0
59   5.2  2.7  3.9  1.4   versicolor       1
73   6.1  2.8  4.7  1.2   versicolor       1
38   4.4  3.0  1.3  0.2       setosa       0
96   5.7  2.9  4.2  1.3   versicolor       1
126  6.2  2.8  4.8  1.8    virginica       2
5    5.4  3.9  1.7  0.4       setosa       0
55   5.7  2.8  4.5  1.3   versicolor       1
61   5.9  3.0  4.2  1.5   versicolor       1
128  6.4  2.8  5.6  2.1    virginica       2
70   5.9  3.2  4.8  1.8   versicolor       1
141  6.9  3.1  5.1  2.3    virginica       2
1    4.9  3.0  1.4  0.2       setosa       0
24   4.8  3.4  1.9  0.2       setosa       0

2

In [9]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
l=[]

In [11]:
for i in df.target:
    if i==0:
        l.append('setosa')
    elif i==1:
        l.append('versicolor')
    else:
        l.append('virginica')

In [12]:
df['named_target']=l

In [13]:
df

       0    1    2    3  target named_target
0    5.1  3.5  1.4  0.2       0       setosa
1    4.9  3.0  1.4  0.2       0       setosa
2    4.7  3.2  1.3  0.2       0       setosa
3    4.6  3.1  1.5  0.2       0       setosa
4    5.0  3.6  1.4  0.2       0       setosa
..   ...  ...  ...  ...     ...          ...
145  6.7  3.0  5.2  2.3       2    virginica
146  6.3  2.5  5.0  1.9       2    virginica
147  6.5  3.0  5.2  2.0       2    virginica
148  6.2  3.4  5.4  2.3       2    virginica
149  5.9  3.0  5.1  1.8       2    virginica

[150 rows x 6 columns]

In [15]:
X,x,Y,y=train_test_split(df.drop('target',axis=1),df.target,test_size=0.3)

df_train=pd.DataFrame(X)
df_train['target']=Y
print(df_train)

df_test=pd.DataFrame(x)
df_test['target']=y
print(df_test)

       0    1    2    3 named_target  target
101  5.8  2.7  5.1  1.9    virginica       2
69   5.6  2.5  3.9  1.1   versicolor       1
128  6.4  2.8  5.6  2.1    virginica       2
134  6.1  2.6  5.6  1.4    virginica       2
64   5.6  2.9  3.6  1.3   versicolor       1
..   ...  ...  ...  ...          ...     ...
1    4.9  3.0  1.4  0.2       setosa       0
142  5.8  2.7  5.1  1.9    virginica       2
122  7.7  2.8  6.7  2.0    virginica       2
90   5.5  2.6  4.4  1.2   versicolor       1
16   5.4  3.9  1.3  0.4       setosa       0

[105 rows x 6 columns]
       0    1    2    3 named_target  target
115  6.4  3.2  5.3  2.3    virginica       2
36   5.5  3.5  1.3  0.2       setosa       0
104  6.5  3.0  5.8  2.2    virginica       2
94   5.6  2.7  4.2  1.3   versicolor       1
127  6.1  3.0  4.9  1.8    virginica       2
55   5.7  2.8  4.5  1.3   versicolor       1
100  6.3  3.3  6.0  2.5    virginica       2
67   5.8  2.7  4.1  1.0   versicolor       1
108  6.7  2.5  5.8  1.8    virginica       2
53   5.5  2.3  4.0  1.3   versicolor       1
19   5.1  3.8  1.5  0.3       setosa       0
3    4.6  3.1  1.5  0.2       setosa       0
68   6.2  2.2  4.5  1.5   versicolor       1
97   6.2  2.9  4.3  1.3   versicolor       1
17   5.1  3.5  1.4  0.3       setosa       0
131  7.9  3.8  6.4  2.0    virginica       2
47   4.6  3.2  1.4  0.2       setosa       0
41   4.5  2.3  1.3  0.3       setosa       0
37   4.9  3.6  1.4  0.1       setosa       0
80   5.5  2.4  3.8  1.1   versicolor       1
58   6.6  2.9  4.6  1.3   versicolor       1
81   5.5  2.4  3.7  1.0   versicolor       1
124  6.7  3.3  5.7  2.1    virginica       2
10   5.4  3.7  1.5  0.2       setosa       0
50   7.0  3.2  4.7  1.4   versicolor       1
54   6.5  2.8  4.6  1.5   versicolor       1
46   5.1  3.8  1.6  0.2       setosa       0
66   5.6  3.0  4.5  1.5   versicolor       1
38   4.4  3.0  1.3  0.2       setosa       0
79   5.7  2.6  3.5  1.0   versicolor       1
114  5.8  2.8  5.1  2.4    virginica       2
130  7.4  2.8  6.1  1.9    virginica       2
86   6.7  3.1  4.7  1.5   versicolor       1
15   5.7  4.4  1.5  0.4       setosa       0
9    4.9  3.1  1.5  0.1       setosa       0
43   5.0  3.5  1.6  0.6       setosa       0
91   6.1  3.0  4.6  1.4   versicolor       1
96   5.7  2.9  4.2  1.3   versicolor       1
147  6.5  3.0  5.2  2.0    virginica       2
6    4.6  3.4  1.4  0.3       setosa       0
56   6.3  3.3  4.7  1.6   versicolor       1
27   5.2  3.5  1.5  0.2       setosa       0
143  6.8  3.2  5.9  2.3    virginica       2
78   6.0  2.9  4.5  1.5   versicolor       1
144  6.7  3.3  5.7  2.5    virginica       2

In [27]:
d={'setosa':0,'versicolor':1,'virginica':2}
l=[]
for i in df.named_target:
    l.append(d[i])

In [28]:
df['trans_target']=l
df

       0    1    2    3  target named_target  trans_target
0    5.1  3.5  1.4  0.2       0       setosa             0
1    4.9  3.0  1.4  0.2       0       setosa             0
2    4.7  3.2  1.3  0.2       0       setosa             0
3    4.6  3.1  1.5  0.2       0       setosa             0
4    5.0  3.6  1.4  0.2       0       setosa             0
..   ...  ...  ...  ...     ...          ...           ...
145  6.7  3.0  5.2  2.3       2    virginica             2
146  6.3  2.5  5.0  1.9       2    virginica             2
147  6.5  3.0  5.2  2.0       2    virginica             2
148  6.2  3.4  5.4  2.3       2    virginica             2
149  5.9  3.0  5.1  1.8       2    virginica             2

[150 rows x 7 columns]

In [29]:
X,x,Y,y=train_test_split(df.drop('target',axis=1),df.target,test_size=0.3)

df_train=pd.DataFrame(X)
df_train['target']=Y
print(df_train)

df_test=pd.DataFrame(x)
df_test['target']=y
print(df_test)

TypeError: Singleton array array(<map object at 0x7f3d3c5bbca0>, dtype=object) cannot be considered a valid collection.